import React from 'react'
import CustomCard from '../../components/CustomCard'


export default function Reports() {
    return (
        <div className='mt-5'>
            {/* <h1>Reports</h1> */}

            <div className='d-flex flex-wrap align-content-center justify-content-center gap-3'>
                <CustomCard title='Driver Performance & Activity Report' description="View trip statistics, driving hours, and alert activity for a driver." onClickPath='drivers' />
                <CustomCard title='Alert Location Analysis Report' description="Analyze alert locations and identify high-risk areas." onClickPath='alerts/per-area' />
                <CustomCard title='Emergency Response Performance Report' description="Monitor emergency response requests and response times." onClickPath='emergency-performance' />
                <CustomCard title='Driver Alert Summary Report' description="Track the number of alerts generated by a specific driver." onClickPath='alerts/per-driver' />
                <CustomCard title='Health Condition Alert Analysis Report' description="Review alerts grouped by detected health conditions." onClickPath='alerts/per-condition' />
                <CustomCard title='Annual Alert Statistics Report' description='Examine yearly trends and alert distribution.' onClickPath='alerts/yearly' />
                <CustomCard title='Fleet Manager Trip Management Report' description="Compare trip activity and outcomes across fleet managers." onClickPath='fleet-managers/trips' />
            </div>
        </div>
    )
}
